// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Forgot: typeof import('./src/components/Forgot.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    'ICarbon:logoGoogle': typeof import('~icons/carbon/logo-google')['default']
    'IIc:roundAdd': typeof import('~icons/ic/round-add')['default']
    'IIc:roundClose': typeof import('~icons/ic/round-close')['default']
    'IIc:roundDarkMode': typeof import('~icons/ic/round-dark-mode')['default']
    'IIc:roundDelete': typeof import('~icons/ic/round-delete')['default']
    'IIc:roundLightMode': typeof import('~icons/ic/round-light-mode')['default']
    'IIc:roundLogout': typeof import('~icons/ic/round-logout')['default']
    'IMdi:github': typeof import('~icons/mdi/github')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NH4: typeof import('naive-ui')['NH4']
    NH6: typeof import('naive-ui')['NH6']
    NImg: typeof import('naive-ui')['NImg']
    NInput: typeof import('naive-ui')['NInput']
    NLink: typeof import('naive-ui')['NLink']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpin: typeof import('naive-ui')['NSpin']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Register: typeof import('./src/components/Register.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    Tracker: typeof import('./src/components/Tracker.vue')['default']
  }
}

export {}
