// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IIc:roundAdd': typeof import('~icons/ic/round-add')['default']
    'IIc:roundAddCircleOutline': typeof import('~icons/ic/round-add-circle-outline')['default']
    'IIc:roundClose': typeof import('~icons/ic/round-close')['default']
    'IIc:roundDarkMode': typeof import('~icons/ic/round-dark-mode')['default']
    'IIc:roundDelete': typeof import('~icons/ic/round-delete')['default']
    'IIc:roundGithubFilled': typeof import('~icons/ic/round-github-filled')['default']
    'IIc:roundLightMode': typeof import('~icons/ic/round-light-mode')['default']
    'IMdi:github': typeof import('~icons/mdi/github')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDynamicInput: typeof import('naive-ui')['NDynamicInput']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalConfig: typeof import('naive-ui')['NGlobalConfig']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLabel: typeof import('naive-ui')['NLabel']
    NModal: typeof import('naive-ui')['NModal']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NProgress: typeof import('naive-ui')['NProgress']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
  }
}

export {}
